import type { Car } from '@/types/car';

export const DEMO_CARS: Car[] = [
  {
    id: 'car_demo_001',
    make: 'Tata',
    modelVariant: 'Nexon EV Max XZ+ Lux',
    registrationNo: 'MH02EV1234',
    odometer: 18500,
    yearOfManufacture: 2023,
    acquisitionDate: '2023-05-15',
    quotingPrice: 1450000,
    rcName: 'TravelNJoy Motors',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Immaculate condition Tata Nexon EV Max with 40.5 kWh battery, sunroof, 360 camera, ventilated seats, and fast charger included.',
    fuel: 'electric',
    transmission: 'automatic',
    color: 'Intensi-Teal',
    features: ['Sunroof', 'Ventilated Seats', '360 Camera', 'Fast Charger', 'Wireless Charging'],
    engine: '30.2 kWh / 143 PS',
    owners: 1,
    bodyType: 'suv',
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: 'car_demo_002',
    make: 'BMW',
    modelVariant: 'X5 xDrive30d M Sport',
    registrationNo: 'DL01CA9999',
    odometer: 32000,
    yearOfManufacture: 2022,
    acquisitionDate: '2022-08-20',
    quotingPrice: 6250000,
    rcName: 'TravelNJoy Luxury Fleet',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Single owner BMW X5 M Sport in Carbon Black Metallic. Panoramic sky lounge, Harman Kardon audio, air suspension, full service history at BMW.',
    fuel: 'diesel',
    transmission: 'automatic',
    color: 'Carbon Black',
    features: ['Panoramic Sunroof', 'Harman Kardon Audio', 'Air Suspension', 'Head-up Display', 'Gesture Control'],
    engine: '3.0L TwinPower Turbo I6',
    owners: 1,
    bodyType: 'suv',
    carType: 'luxury',
    createdAt: '2024-01-12T12:00:00Z',
  },
  {
    id: 'car_demo_003',
    make: 'Hyundai',
    modelVariant: 'Creta 1.5 SX(O) Diesel AT',
    registrationNo: 'KA05MH5678',
    odometer: 24000,
    yearOfManufacture: 2023,
    acquisitionDate: '2023-02-10',
    quotingPrice: 1680000,
    rcName: 'TravelNJoy Motors',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Top-spec Hyundai Creta with Bose 8-speaker system, ADAS safety suite, panoramic sunroof, and cooled front seats.',
    fuel: 'diesel',
    transmission: 'automatic',
    color: 'Titan Grey',
    features: ['Bose Premium Audio', 'Level 2 ADAS', 'Panoramic Sunroof', 'Ambient Lighting', 'Air Purifier'],
    engine: '1.5L U2 CRDi',
    owners: 1,
    bodyType: 'suv',
    createdAt: '2024-01-15T09:30:00Z',
  },
  {
    id: 'car_demo_004',
    make: 'Maruti Suzuki',
    modelVariant: 'Swift ZXi Plus AMT',
    registrationNo: 'MH12TR4321',
    odometer: 14200,
    yearOfManufacture: 2023,
    acquisitionDate: '2023-09-01',
    quotingPrice: 790000,
    rcName: 'TravelNJoy Motors',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Highly economical Maruti Suzuki Swift ZXi+ Dual Tone with SmartPlay Pro+ touchscreen, LED projector headlamps, and push button start.',
    fuel: 'petrol',
    transmission: 'automatic',
    color: 'Sizzling Red with Black Roof',
    features: ['Touchscreen Infotainment', 'Cruise Control', 'LED Headlamps', 'Automatic Climate Control'],
    engine: '1.2L K-Series DualJet',
    owners: 1,
    bodyType: 'hatchback',
    createdAt: '2024-01-18T14:20:00Z',
  },
  {
    id: 'car_demo_005',
    make: 'Mahindra',
    modelVariant: 'Scorpio-N Z8L Diesel 4X4 AT',
    registrationNo: 'HR26EN8888',
    odometer: 29000,
    yearOfManufacture: 2023,
    acquisitionDate: '2023-04-11',
    quotingPrice: 2240000,
    rcName: 'TravelNJoy Motors',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Rugged 7-seater Scorpio-N Z8L with 4XPLOR terrain response mode, Sony 12-speaker 3D audio, and captain seats.',
    fuel: 'diesel',
    transmission: 'automatic',
    color: 'Deep Forest',
    features: ['4X4 Terrain Response', 'Sony 12-Speaker Audio', 'Captain Seats', 'Wireless Android Auto / CarPlay'],
    engine: '2.2L mHawk Diesel (175 PS)',
    owners: 1,
    bodyType: 'suv',
    createdAt: '2024-01-20T11:15:00Z',
  },
  {
    id: 'car_demo_006',
    make: 'Toyota',
    modelVariant: 'Innova Crysta 2.4 VX 7 STR',
    registrationNo: 'UP16AB5555',
    odometer: 48000,
    yearOfManufacture: 2022,
    acquisitionDate: '2022-11-05',
    quotingPrice: 1980000,
    rcName: 'TravelNJoy Motors',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Unmatched reliability Toyota Innova Crysta. Maintained exclusively at Toyota authorized service station with complete log book.',
    fuel: 'diesel',
    transmission: 'manual',
    color: 'Super White',
    features: ['7 Seater Captain Chairs', 'Automatic Climate Control', 'Push Start', 'Rear AC Vents'],
    engine: '2.4L GD Diesel',
    owners: 1,
    bodyType: 'muv_mpv',
    createdAt: '2024-01-22T16:00:00Z',
  },
  {
    id: 'car_demo_007',
    make: 'Honda',
    modelVariant: 'City 1.5 i-VTEC ZX CVT',
    registrationNo: 'DL08CX1212',
    odometer: 21500,
    yearOfManufacture: 2022,
    acquisitionDate: '2022-06-18',
    quotingPrice: 1290000,
    rcName: 'TravelNJoy Motors',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Executive sedan Honda City ZX with LaneWatch camera, full LED headlights, leatherette upholstery, and electric sunroof.',
    fuel: 'petrol',
    transmission: 'cvt',
    color: 'Golden Brown Metallic',
    features: ['Honda Sensing LaneWatch', 'Sunroof', 'Full LED Lights', 'Leather Upholstery'],
    engine: '1.5L i-VTEC DOHC',
    owners: 1,
    bodyType: 'sedan',
    createdAt: '2024-01-25T08:45:00Z',
  },
  {
    id: 'car_demo_008',
    make: 'Mercedes-Benz',
    modelVariant: 'C-Class C 220d Progressive',
    registrationNo: 'MH01DA7777',
    odometer: 19500,
    yearOfManufacture: 2023,
    acquisitionDate: '2023-07-22',
    quotingPrice: 5150000,
    rcName: 'TravelNJoy Luxury Fleet',
    status: 'available',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800&auto=format&fit=crop&q=60'
    ],
    description: 'Latest generation Mercedes-Benz C-Class with vertical 11.9-inch MBUX touchscreen, 64-color ambient lighting, and Burmester sound system.',
    fuel: 'diesel',
    transmission: 'automatic',
    color: 'Mojave Silver',
    features: ['MBUX 11.9" Screen', 'Burmester 3D Sound', '64-Color Ambient Light', 'Digital Light Headlamps'],
    engine: '2.0L Turbo Diesel + 48V Mild Hybrid',
    owners: 1,
    bodyType: 'sedan',
    carType: 'luxury',
    createdAt: '2024-01-28T10:30:00Z',
  }
];
