import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatMileage(mileage: number): string {
  return new Intl.NumberFormat('en-IN').format(mileage) + ' km';
}

export function generateId(): string {
  return `car_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

export function generateMessageId(): string {
  return `msg_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

export function generateCustomerId(): string {
  return `cust_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
}

// Demo cars for when Firebase is not configured
export const DEMO_CARS: import('@/types/car').Car[] = [
  {
    id: 'demo_1',
    make: 'Toyota',
    modelVariant: 'Camry XLE',
    yearOfManufacture: 2021,
    quotingPrice: 2200000,
    odometer: 32000,
    fuel: 'petrol',
    transmission: 'automatic',
    color: 'Pearl White',
    description: 'Pristine condition Toyota Camry with full service history. One owner. All features intact including sunroof, leather seats, and advanced safety systems.',
    images: ['/car-sedan.png'],
    status: 'available',
    features: ['Sunroof', 'Leather Seats', 'Backup Camera', 'Bluetooth', 'Cruise Control', 'Lane Assist'],
    engine: '2.5L 4-cylinder',
    owners: 1,
    rcName: 'Rahul T.',
    condition: 'Excellent',
    carType: 'Sedan',
    createdAt: '2024-01-15T10:00:00Z',
    registrationNo: 'MH02AB1234',
    acquisitionDate: '2024-01-10T10:00:00Z',
  },
  {
    id: 'demo_2',
    make: 'BMW',
    modelVariant: 'X5 xDrive40i',
    yearOfManufacture: 2022,
    quotingPrice: 6500000,
    odometer: 18000,
    fuel: 'diesel',
    transmission: 'automatic',
    color: 'Midnight Black',
    description: 'Luxury BMW X5 with panoramic sunroof, 360 camera, premium Harman Kardon sound system. Loaded with all options. Under warranty.',
    images: ['/car-suv.png'],
    status: 'available',
    features: ['Panoramic Sunroof', '360 Camera', 'Harman Kardon Audio', 'Heated Seats', 'Ventilated Seats', 'Heads-Up Display'],
    engine: '3.0L 6-cylinder Turbo Diesel',
    owners: 1,
    rcName: 'Anita M.',
    condition: 'Like New',
    carType: 'SUV',
    createdAt: '2024-02-20T10:00:00Z',
    registrationNo: 'DL01C9876',
    acquisitionDate: '2024-02-15T10:00:00Z',
  },
  {
    id: 'demo_3',
    make: 'Honda',
    modelVariant: 'City VX',
    yearOfManufacture: 2020,
    quotingPrice: 980000,
    odometer: 45000,
    fuel: 'petrol',
    transmission: 'cvt',
    color: 'Lunar Silver',
    description: 'Well-maintained Honda City CVT. Excellent fuel economy. Ideal for city driving and highway cruising. Full service records available.',
    images: ['/car-sedan.png'],
    status: 'available',
    features: ['Lane Watch Camera', 'Touchscreen Infotainment', 'Reverse Camera', 'Automatic Climate Control'],
    engine: '1.5L i-VTEC',
    owners: 2,
    rcName: 'Sanjay P.',
    condition: 'Good',
    carType: 'Sedan',
    createdAt: '2024-03-10T10:00:00Z',
    registrationNo: 'KA03MN4567',
    acquisitionDate: '2024-03-01T10:00:00Z',
  },
  {
    id: 'demo_4',
    make: 'Hyundai',
    modelVariant: 'Creta SX(O)',
    yearOfManufacture: 2023,
    quotingPrice: 1750000,
    odometer: 12000,
    fuel: 'diesel',
    transmission: 'automatic',
    color: 'Typhoon Silver',
    description: 'Nearly new Hyundai Creta SX(O) fully loaded trim. Panoramic sunroof, ventilated seats, BlueLink connected features, and ADAS suite.',
    images: ['/car-suv.png'],
    status: 'reserved',
    features: ['Panoramic Sunroof', 'ADAS Safety Suite', 'BlueLink Connected', 'Ventilated Front Seats', 'Wireless Charging'],
    engine: '1.5L U2 CRDi Diesel',
    owners: 1,
    rcName: 'Vikram S.',
    condition: 'Excellent',
    carType: 'SUV',
    createdAt: '2024-04-05T10:00:00Z',
    registrationNo: 'HR26DQ1122',
    acquisitionDate: '2024-04-01T10:00:00Z',
  },
  {
    id: 'demo_5',
    make: 'Tata',
    modelVariant: 'Nexon EV Max',
    yearOfManufacture: 2023,
    quotingPrice: 1600000,
    odometer: 8000,
    fuel: 'electric',
    transmission: 'automatic',
    color: 'Flame Red',
    description: 'Tata Nexon EV Max with 437km certified range. Fast charging capability. V2L feature. Still under manufacturer warranty.',
    images: ['/car-suv.png'],
    status: 'available',
    features: ['437km Range', 'Fast Charging', 'Vehicle-to-Load', 'Air Purifier', 'Connected Tech', 'Wireless Charging'],
    engine: 'Electric Motor - 143 PS',
    owners: 1,
    rcName: 'Priya K.',
    condition: 'Like New',
    carType: 'SUV',
    createdAt: '2024-05-01T10:00:00Z',
    registrationNo: 'TS07EZ5544',
    acquisitionDate: '2024-04-20T10:00:00Z',
  },
  {
    id: 'demo_6',
    make: 'Maruti',
    modelVariant: 'Swift ZXi',
    yearOfManufacture: 2019,
    quotingPrice: 620000,
    odometer: 58000,
    fuel: 'petrol',
    transmission: 'manual',
    color: 'Solid Red',
    description: 'Reliable and economical Maruti Swift ZXi. Excellent city car with low maintenance cost. Full service history available.',
    images: ['/car-sedan.png'],
    status: 'sold',
    features: ['SmartPlay Infotainment', 'Rear Parking Sensors', 'Dual Airbags', 'ABS', 'EBD'],
    engine: '1.2L K-Series',
    owners: 1,
    rcName: 'Amit D.',
    condition: 'Good',
    carType: 'Hatchback',
    createdAt: '2024-01-25T10:00:00Z',
    registrationNo: 'RJ14CV3322',
    acquisitionDate: '2024-01-15T10:00:00Z',
    buyerName: 'Ramesh Singh',
    buyerPAN: 'ABCDE1234F',
    buyerAadhar: '1234 5678 9012',
    buyerAddress: '123 Main St, Jaipur',
    soldDate: '2024-02-10T10:00:00Z',
  },
  {
    id: 'demo_7',
    make: 'Maruti Suzuki',
    modelVariant: 'Celerio VXI',
    yearOfManufacture: 2015,
    quotingPrice: 350000,
    odometer: 45000,
    fuel: 'petrol',
    transmission: 'manual',
    color: 'Silky Silver',
    description: 'Silver Maruti Suzuki Celerio VXI in good condition. Affordable and practical hatchback.',
    images: [
      '/MS Celerio demo/1 (2).jpeg',
      '/MS Celerio demo/1 (1).jpeg',
      '/MS Celerio demo/1 (4).jpeg',
      '/MS Celerio demo/1 (5).jpeg',
      '/MS Celerio demo/1 (6).jpeg',
      '/MS Celerio demo/1 (8).jpeg',
    ],
    status: 'sold',
    features: ['Power Steering', 'AC', 'Front Power Windows'],
    engine: '998.00 CC',
    owners: 1,
    rcName: 'DEBABRATA CHOWDHURY',
    ownerAddress: 'NEAR APIL , BL-II, E-153, NAMSAI, NAMSAI, NAMSAI-ARUNACHAL PRADESH-792103',
    condition: 'Used - Good',
    carType: 'Hatchback',
    registrationNo: 'AR11A3021',
    chassisNo: 'MA3ETDE1S00192979',
    engineNo: 'K10BN1844928',
    acquisitionDate: '2024-06-19',
    buyerName: 'Arup Kakoty',
    buyerAadhar: '9698 6745 2344',
    buyerPAN: 'DBQPK8679M',
    buyerAddress: 'C/O: So Late Sonaram Kakoty, BORDUBI BAZAR, Bordubi Rev. Town., Tinsukia, Assam, 786601',
    soldDate: '2024-07-10T10:00:00Z',
    createdAt: '2024-06-19T10:00:00Z',
  },
  {
    id: 'demo_8',
    make: 'Tata',
    modelVariant: 'Harrier XT',
    yearOfManufacture: 2019,
    quotingPrice: 750000,
    odometer: 65123,
    fuel: 'diesel',
    transmission: 'manual',
    color: 'Tel Grey',
    description: 'Tata Harrier XT (MUV) in excellent condition. Well maintained with all original features intact. Registered in Namsai, Arunachal Pradesh. Tata Motors Assured vehicle with original RC and insurance. 1956 CC Diesel engine. Road tax paid till 2029.',
    images: [
      '/nexon/1.jpeg',
      '/nexon/2.jpeg',
      '/nexon/3.jpeg',
      '/nexon/5.jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.42 AM (1).jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.44 AM (1).jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.44 AM (2).jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.45 AM.jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.47 AM (1).jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.48 AM (1).jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.49 AM.jpeg',
      '/nexon/WhatsApp Image 2026-07-15 at 10.54.51 AM.jpeg',
    ],
    status: 'sold',
    features: ['Power Steering', 'AC', 'Reverse Camera', 'Touchscreen Infotainment', 'Roof Rails', 'Alloy Wheels', 'Fog Lamps', 'ABS', 'Dual Airbags'],
    engine: '1956 CC Kryotec Diesel',
    owners: 1,
    rcName: 'Tangyan Simai',
    ownerAddress: 'Vill: Kovin, PO/PS: Jairampur, Dist. Changlang, Arunachal Pradesh',
    condition: 'Used - Good',
    carType: 'SUV',
    registrationNo: 'AR-20-6655',
    chassisNo: 'MAT631121KPF60171',
    engineNo: '46336890-4048600',
    acquisitionDate: '2026-07-01',
    soldDate: '2026-07-15T10:00:00Z',
    createdAt: '2026-07-15T10:00:00Z',
    buyerName: 'Demo Buyer',
    buyerPAN: 'XYZPDQ99',
    buyerAadhar: '1111 2222 3333',
    buyerAddress: 'Demo City'
  },
];
